puts "🇧🇴 Creating nationalities"

nationality_count = 0

nationalities = [
  { code: "AFG", name: "Afghane (Afghanistan)"},
  { code: "ALB", name: "Albanaise (Albanie)"},
  { code: "DZA", name: "Algérienne (Algérie)"},
  { code: "DEU", name: "Allemande (Allemagne)"},
  { code: "USA", name: "Americaine (États-Unis)"},
  { code: "AND", name: "Andorrane (Andorre)"},
  { code: "AGO", name: "Angolaise (Angola)"},
  { code: "ATG", name: "Antiguaise-et-Barbudienne (Antigua-et-Barbuda)"},
  { code: "ARG", name: "Argentine (Argentine)"},
  { code: "ARM", name: "Armenienne (Arménie)"},
  { code: "AUS", name: "Australienne (Australie)"},
  { code: "AUT", name: "Autrichienne (Autriche)"},
  { code: "AZE", name: "Azerbaïdjanaise (Azerbaïdjan)"},
  { code: "BHS", name: "Bahamienne (Bahamas)"},
  { code: "BHR", name: "Bahreinienne (Bahreïn)"},
  { code: "BGD", name: "Bangladaise (Bangladesh)"},
  { code: "BRB", name: "Barbadienne (Barbade)"},
  { code: "BEL", name: "Belge (Belgique)"},
  { code: "BLZ", name: "Belizienne (Belize)"},
  { code: "BEN", name: "Béninoise (Bénin)"},
  { code: "BTN", name: "Bhoutanaise (Bhoutan)"},
  { code: "BLR", name: "Biélorusse (Biélorussie)"},
  { code: "MMR", name: "Birmane (Birmanie)"},
  { code: "GNB", name: "Bissau-Guinéenne (Guinée-Bissau)"},
  { code: "BOL", name: "Bolivienne (Bolivie)"},
  { code: "BIH", name: "Bosnienne (Bosnie-Herzégovine)"},
  { code: "BWA", name: "Botswanaise (Botswana)"},
  { code: "BRA", name: "Brésilienne (Brésil)"},
  { code: "GBR", name: "Britannique (Royaume-Uni)"},
  { code: "BRN", name: "Brunéienne (Brunéi)"},
  { code: "BGR", name: "Bulgare (Bulgarie)"},
  { code: "BFA", name: "Burkinabée (Burkina)"},
  { code: "BDI", name: "Burundaise (Burundi)"},
  { code: "KHM", name: "Cambodgienne (Cambodge)"},
  { code: "CMR", name: "Camerounaise (Cameroun)"},
  { code: "CAN", name: "Canadienne (Canada)"},
  { code: "CPV", name: "Cap-verdienne (Cap-Vert)"},
  { code: "CAF", name: "Centrafricaine (Centrafrique)"},
  { code: "CHL", name: "Chilienne (Chili)"},
  { code: "CHN", name: "Chinoise (Chine)"},
  { code: "CYP", name: "Chypriote (Chypre)"},
  { code: "COL", name: "Colombienne (Colombie)"},
  { code: "COM", name: "Comorienne (Comores)"},
  { code: "COG", name: "Congolaise (Congo-Brazzaville)"},
  { code: "COD", name: "Congolaise (Congo-Kinshasa)"},
  { code: "COK", name: "Cookienne (Îles Cook)"},
  { code: "CRI", name: "Costaricaine (Costa Rica)"},
  { code: "HRV", name: "Croate (Croatie)"},
  { code: "CUB", name: "Cubaine (Cuba)"},
  { code: "DNK", name: "Danoise (Danemark)"},
  { code: "DJI", name: "Djiboutienne (Djibouti)"},
  { code: "DOM", name: "Dominicaine (République dominicaine)"},
  { code: "DMA", name: "Dominiquaise (Dominique)"},
  { code: "EGY", name: "Égyptienne (Égypte)"},
  { code: "ARE", name: "Émirienne (Émirats arabes unis)"},
  { code: "GNQ", name: "Équato-guineenne (Guinée équatoriale)"},
  { code: "ECU", name: "Équatorienne (Équateur)"},
  { code: "ERI", name: "Érythréenne (Érythrée)"},
  { code: "ESP", name: "Espagnole (Espagne)"},
  { code: "TLS", name: "Est-timoraise (Timor-Leste)"},
  { code: "EST", name: "Estonienne (Estonie)"},
  { code: "ETH", name: "Éthiopienne (Éthiopie)"},
  { code: "FJI", name: "Fidjienne (Fidji)"},
  { code: "FIN", name: "Finlandaise (Finlande)"},
  { code: "FRA", name: "Française (France)"},
  { code: "GAB", name: "Gabonaise (Gabon)"},
  { code: "GMB", name: "Gambienne (Gambie)"},
  { code: "GEO", name: "Georgienne (Géorgie)"},
  { code: "GHA", name: "Ghanéenne (Ghana)"},
  { code: "GRD", name: "Grenadienne (Grenade)"},
  { code: "GTM", name: "Guatémaltèque (Guatemala)"},
  { code: "GIN", name: "Guinéenne (Guinée)"},
  { code: "GUY", name: "Guyanienne (Guyana)"},
  { code: "HTI", name: "Haïtienne (Haïti)"},
  { code: "GRC", name: "Hellénique (Grèce)"},
  { code: "HND", name: "Hondurienne (Honduras)"},
  { code: "HUN", name: "Hongroise (Hongrie)"},
  { code: "IND", name: "Indienne (Inde)"},
  { code: "IDN", name: "Indonésienne (Indonésie)"},
  { code: "IRQ", name: "Irakienne (Iraq)"},
  { code: "IRN", name: "Iranienne (Iran)"},
  { code: "IRL", name: "Irlandaise (Irlande)"},
  { code: "ISL", name: "Islandaise (Islande)"},
  { code: "ISR", name: "Israélienne (Israël)"},
  { code: "ITA", name: "Italienne (Italie)"},
  { code: "CIV", name: "Ivoirienne (Côte d'Ivoire)"},
  { code: "JAM", name: "Jamaïcaine (Jamaïque)"},
  { code: "JPN", name: "Japonaise (Japon)"},
  { code: "JOR", name: "Jordanienne (Jordanie)"},
  { code: "KAZ", name: "Kazakhstanaise (Kazakhstan)"},
  { code: "KEN", name: "Kenyane (Kenya)"},
  { code: "KGZ", name: "Kirghize (Kirghizistan)"},
  { code: "KIR", name: "Kiribatienne (Kiribati)"},
  { code: "KNA", name: "Kittitienne et Névicienne (Saint-Christophe-et-Niévès)"},
  { code: "KWT", name: "Koweïtienne (Koweït)"},
  { code: "LAO", name: "Laotienne (Laos)"},
  { code: "LSO", name: "Lesothane (Lesotho)"},
  { code: "LVA", name: "Lettone (Lettonie)"},
  { code: "LBN", name: "Libanaise (Liban)"},
  { code: "LBR", name: "Libérienne (Libéria)"},
  { code: "LBY", name: "Libyenne (Libye)"},
  { code: "LIE", name: "Liechtensteinoise (Liechtenstein)"},
  { code: "LTU", name: "Lituanienne (Lituanie)"},
  { code: "LUX", name: "Luxembourgeoise (Luxembourg)"},
  { code: "MKD", name: "Macédonienne (Macédoine)"},
  { code: "MYS", name: "Malaisienne (Malaisie)"},
  { code: "MWI", name: "Malawienne (Malawi)"},
  { code: "MDV", name: "Maldivienne (Maldives)"},
  { code: "MDG", name: "Malgache (Madagascar)"},
  { code: "MLI", name: "Maliennes (Mali)"},
  { code: "MLT", name: "Maltaise (Malte)"},
  { code: "MAR", name: "Marocaine (Maroc)"},
  { code: "MHL", name: "Marshallaise (Îles Marshall)"},
  { code: "MUS", name: "Mauricienne (Maurice)"},
  { code: "MRT", name: "Mauritanienne (Mauritanie)"},
  { code: "MEX", name: "Mexicaine (Mexique)"},
  { code: "FSM", name: "Micronésienne (Micronésie)"},
  { code: "MDA", name: "Moldave (Moldovie)"},
  { code: "MCO", name: "Monegasque (Monaco)"},
  { code: "MNG", name: "Mongole (Mongolie)"},
  { code: "MNE", name: "Monténégrine (Monténégro)"},
  { code: "MOZ", name: "Mozambicaine (Mozambique)"},
  { code: "NAM", name: "Namibienne (Namibie)"},
  { code: "NRU", name: "Nauruane (Nauru)"},
  { code: "NLD", name: "Néerlandaise (Pays-Bas)"},
  { code: "NZL", name: "Néo-Zélandaise (Nouvelle-Zélande)"},
  { code: "NPL", name: "Népalaise (Népal)"},
  { code: "NIC", name: "Nicaraguayenne (Nicaragua)"},
  { code: "NGA", name: "Nigériane (Nigéria)"},
  { code: "NER", name: "Nigérienne (Niger)"},
  { code: "NIU", name: "Niuéenne (Niue)"},
  { code: "PRK", name: "Nord-coréenne (Corée du Nord)"},
  { code: "NOR", name: "Norvégienne (Norvège)"},
  { code: "OMN", name: "Omanaise (Oman)"},
  { code: "UGA", name: "Ougandaise (Ouganda)"},
  { code: "UZB", name: "Ouzbéke (Ouzbékistan)"},
  { code: "PAK", name: "Pakistanaise (Pakistan)"},
  { code: "PLW", name: "Palaosienne (Palaos)"},
  { code: "PSE", name: "Palestinienne (Palestine)"},
  { code: "PAN", name: "Panaméenne (Panama)"},
  { code: "PNG", name: "Papouane-Néo-Guinéenne (Papouasie-Nouvelle-Guinée)"},
  { code: "PRY", name: "Paraguayenne (Paraguay)"},
  { code: "PER", name: "Péruvienne (Pérou)"},
  { code: "PHL", name: "Philippine (Philippines)"},
  { code: "POL", name: "Polonaise (Pologne)"},
  { code: "PRT", name: "Portugaise (Portugal)"},
  { code: "QAT", name: "Qatarienne (Qatar)"},
  { code: "ROU", name: "Roumaine (Roumanie)"},
  { code: "RUS", name: "Russe (Russie)"},
  { code: "RWA", name: "Rwandaise (Rwanda)"},
  { code: "LCA", name: "Saint-Lucienne (Sainte-Lucie)"},
  { code: "SMR", name: "Saint-Marinaise (Saint-Marin)"},
  { code: "VCT", name: "Saint-Vincentaise et Grenadine (Saint-Vincent-et-les Grenadines)"},
  { code: "SLB", name: "Salomonaise (Îles Salomon)"},
  { code: "SLV", name: "Salvadorienne (Salvador)"},
  { code: "WSM", name: "Samoane (Samoa)"},
  { code: "STP", name: "Santoméenne (Sao Tomé-et-Principe)"},
  { code: "SAU", name: "Saoudienne (Arabie saoudite)"},
  { code: "SEN", name: "Sénégalaise (Sénégal)"},
  { code: "SRB", name: "Serbe (Serbie)"},
  { code: "SYC", name: "Seychelloise (Seychelles)"},
  { code: "SLE", name: "Sierra-Léonaise (Sierra Leone)"},
  { code: "SGP", name: "Singapourienne (Singapour)"},
  { code: "SVK", name: "Slovaque (Slovaquie)"},
  { code: "SVN", name: "Slovène (Slovénie)"},
  { code: "SOM", name: "Somalienne (Somalie)"},
  { code: "SDN", name: "Soudanaise (Soudan)"},
  { code: "LKA", name: "Sri-Lankaise (Sri Lanka)"},
  { code: "ZAF", name: "Sud-Africaine (Afrique du Sud)"},
  { code: "KOR", name: "Sud-Coréenne (Corée du Sud)"},
  { code: "SSD", name: "Sud-Soudanaise (Soudan du Sud)"},
  { code: "SWE", name: "Suédoise (Suède)"},
  { code: "CHE", name: "Suisse (Suisse)"},
  { code: "SUR", name: "Surinamaise (Suriname)"},
  { code: "SWZ", name: "Swazie (Swaziland)"},
  { code: "SYR", name: "Syrienne (Syrie)"},
  { code: "TJK", name: "Tadjike (Tadjikistan)"},
  { code: "TZA", name: "Tanzanienne (Tanzanie)"},
  { code: "TCD", name: "Tchadienne (Tchad)"},
  { code: "CZE", name: "Tchèque (Tchéquie)"},
  { code: "THA", name: "Thaïlandaise (Thaïlande)"},
  { code: "TGO", name: "Togolaise (Togo)"},
  { code: "TON", name: "Tonguienne (Tonga)"},
  { code: "TTO", name: "Trinidadienne (Trinité-et-Tobago)"},
  { code: "TUN", name: "Tunisienne (Tunisie)"},
  { code: "TKM", name: "Turkmène (Turkménistan)"},
  { code: "TUR", name: "Turque (Turquie)"},
  { code: "TUV", name: "Tuvaluane (Tuvalu)"},
  { code: "UKR", name: "Ukrainienne (Ukraine)"},
  { code: "URY", name: "Uruguayenne (Uruguay)"},
  { code: "VUT", name: "Vanuatuane (Vanuatu)"},
  { code: "VAT", name: "Vaticane (Vatican)"},
  { code: "VEN", name: "Vénézuélienne (Venezuela)"},
  { code: "VNM", name: "Vietnamienne (Viêt Nam)"},
  { code: "YEM", name: "Yéménite (Yémen)"},
  { code: "ZMB", name: "Zambienne (Zambie)"},
  { code: "ZWE", name: "Zimbabwéenne (Zimbabwe)"}
]

nationalities.each do |nationality|
  Nationality.create!(
    name: nationality[:name],
    code: nationality[:code]
  )
  nationality_count += 1
  puts "-- Created nationality: #{Nationality.last.name}"
end

puts "✅ Created #{Nationality.count} nationalities in total"
