load "db/seeds/destroy_all.rb"
load "db/seeds/nationalities.rb"
load "db/seeds/users.rb"
load "db/seeds/composers.rb"
load "db/seeds/works_greif.rb"
load "db/seeds/works_prokofiev.rb"
load "db/seeds/movements.rb"
load "db/seeds/quotes.rb"
